First minimal version with Meta-Data POST/GET
dojot/image-manager pull request #1
Opened 2018-01-17 20:44 UTC by jsiloto

This was entirely built by modifying dojot/device-manager and some leftover code may still be around.
Also, the PR in https://github.com/dojot/docker-compose/pull/29 is needed for testing

2018-01-18 10:24 UTC, mmagr requested changes
As for testing, in light of the troubles we had when setting up the dev environment, a PR dojot/device-manager#21 has been submitted.

Basically what it does is to create a local compose file allowing for easier testing of the isolated service. I think one might benefit from that here too.

2018-01-18 10:24 UTC, mmagr commented on ImageManager/ImageManager.py
> +    FIWARE backend
we're not configuring fiware, are we?

2018-01-18 10:24 UTC, mmagr commented on ImageManager/ImageManager.py
> +        result = {
why not have this include creation/update dates as well?
and if doing so, why not have marshmallow do this for us?

2018-01-18 10:24 UTC, mmagr commented on ImageManager/ImageManager.py
> +        print(request)
I think it'd be better to make use of LOGGER for log generation.
If this is just left over from development, we could remove it.

2018-01-18 10:24 UTC, mmagr commented on ImageManager/DatabaseModels.py
> +print(app.config['SQLALCHEMY_DATABASE_URI'])
This should be removed, shouldn't it?

2018-01-18 10:24 UTC, mmagr commented on ImageManager/ImageManager.py
> +        # # TODO remove this in favor of kafka as data broker....
I think those can be safely removed from code - this service should require no events of that nature being sent at this time.

2018-01-18 10:24 UTC, mmagr commented on ImageManager/ImageManager.py
> +        print("Operation Successful - result: {}".format(result))
the same note on logging here

2018-01-18 10:24 UTC, mmagr commented on ImageManager/conf.py
> +        self.kafka_host = os.environ.get('KAFKA_HOST', kafka_host)
we might want to remove kafka config

2018-01-18 10:24 UTC, mmagr commented on ImageManager/conf.py
> +                 kafka_host="kafka",
we might want to remove kafka config

2018-01-18 10:24 UTC, mmagr commented on ImageManager/utils.py
> +def create_id():
This could be removed

2018-01-18 10:24 UTC, mmagr commented on LICENSE
> +  Some images are designed to deny users access to install or run
this must be rolled back (we shouldn't tinker with the license). Perhaps this is the result of a "replace all"?

2018-01-18 10:24 UTC, mmagr commented on setup.py
> +    author='Matheus Magalhaes',
hmm, this should be Juliano Siloto, right? :thinking:

2018-01-18 10:24 UTC, mmagr commented on tests/autotest.sh
> +#!/bin/bash
This file should be removed. I don't suppose it works even for device manager by now.
(furthermore, if anyone is to do this sort of automatic testing, it's Travis, not Jenkins)

2018-01-18 10:24 UTC, mmagr commented on tests/docker-compose.yaml
> +version: '2'
Same as for `tests/autotest.sh` goes here.

2018-01-19 16:41 UTC, jsiloto commented
All suggested changes were made except for the local docker-compose addition.
The PR dojot/device-manager#21 is enought to get the service up and running but the service is inacessible from outside world

2018-01-19 22:23 UTC, mmagr approved these changes

2018-01-21 23:37 UTC, jsiloto commented
My bad, the previous reply was wrong due my poor understanding of docker. But since the whole point of how-to's is for people who don't know the inner workings of the system, I've opened an issue related to this: dojot/image-manager/issues/3

2018-01-21 23:37 UTC, merged